version: '3.9'
services:
  nest-app:
    container_name: ballot-dapp-api
    build:
      context: ./api
      dockerfile: Dockerfile
    image: ballot-api
    restart: always
    ports:
      - 3001:3001
    volumes:
      - ./api:/usr/src
      - /usr/src/node-modules
  next-app:
    container_name: ballot-dapp-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: ballot-client
    restart: always
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/usr/src
      - /usr/src/node-modules
      - /usr/src/.next